"""init_db_schemas

Revision ID: 4a7ef0888be4
Revises: 
Create Date: 2026-03-09 23:52:09.164654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7ef0888be4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_uri', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('content_body', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_records_source_uri'), 'article_records', ['source_uri'], unique=True)
    op.create_table('sentiment_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('primary_sentiment', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_results_article_id'), 'sentiment_results', ['article_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_results_article_id'), table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_article_records_source_uri'), table_name='article_records')
    op.drop_table('article_records')
    # ### end Alembic commands ###
